package mictgui;
/*This is the sample client gui that will display the toolbar and canvas.
 * @author  Donald Huckle
 */
public class ClientPanel extends javax.swing.JApplet {

    /** Initializes the applet ClientPanel */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolbarPanel = new javax.swing.JPanel();
        ZoomInButton = new javax.swing.JButton();
        ZoomOutButton = new javax.swing.JButton();
        PencilButton = new javax.swing.JButton();
        CopyButton = new javax.swing.JButton();
        CutButton = new javax.swing.JButton();
        PasteButton = new javax.swing.JButton();
        CanvasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        ToolbarPanel.setLayout(new javax.swing.BoxLayout(ToolbarPanel, javax.swing.BoxLayout.LINE_AXIS));

        ZoomInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/ZoomIn-32.png"))); // NOI18N
        ZoomInButton.setPreferredSize(new java.awt.Dimension(32, 32));
        ZoomInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomInButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(ZoomInButton);

        ZoomOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/ZoomOut-32.png"))); // NOI18N
        ZoomOutButton.setPreferredSize(new java.awt.Dimension(32, 32));
        ZoomOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomOutButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(ZoomOutButton);

        PencilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Edit-32.png"))); // NOI18N
        PencilButton.setPreferredSize(new java.awt.Dimension(32, 32));
        PencilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PencilButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(PencilButton);

        CopyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Copy-32.png"))); // NOI18N
        CopyButton.setPreferredSize(new java.awt.Dimension(32, 32));
        CopyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CopyButtonMouseClicked(evt);
            }
        });
        CopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(CopyButton);

        CutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Cut-32.png"))); // NOI18N
        CutButton.setPreferredSize(new java.awt.Dimension(32, 32));
        CutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(CutButton);

        PasteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Paste-32.png"))); // NOI18N
        PasteButton.setPreferredSize(new java.awt.Dimension(32, 32));
        PasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(PasteButton);

        jLabel1.setText("Canvas View");
        CanvasPanel.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CanvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ToolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(CanvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void CopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CopyButtonActionPerformed

private void CopyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CopyButtonMouseClicked
//CopyButton has been clicked.    
}//GEN-LAST:event_CopyButtonMouseClicked

private void ZoomInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomInButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ZoomInButtonActionPerformed

private void ZoomOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomOutButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ZoomOutButtonActionPerformed

private void PencilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PencilButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_PencilButtonActionPerformed

private void CutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CutButtonActionPerformed

private void PasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_PasteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CanvasPanel;
    private javax.swing.JButton CopyButton;
    private javax.swing.JButton CutButton;
    private javax.swing.JButton PasteButton;
    private javax.swing.JButton PencilButton;
    private javax.swing.JPanel ToolbarPanel;
    private javax.swing.JButton ZoomInButton;
    private javax.swing.JButton ZoomOutButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
