/*
 * Tools.java
 *
 * Created on October 1, 2010, 7:32 PM
 */

package mictgui;

/**
 *
 * @author  radicaledward
 */
public class Tools extends javax.swing.JApplet {

    /** Initializes the applet Tools */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CopyButton = new javax.swing.JButton();
        CutButton = new javax.swing.JButton();
        ZoomInButton = new javax.swing.JButton();
        ZoomOutButton = new javax.swing.JButton();
        PencilButton = new javax.swing.JButton();
        PasteButton = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        CopyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Copy-32.png"))); // NOI18N
        CopyButton.setPreferredSize(new java.awt.Dimension(32, 32));
        CopyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CopyButtonMouseClicked(evt);
            }
        });
        CopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CopyButton);

        CutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Cut-32.png"))); // NOI18N
        CutButton.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(CutButton);

        ZoomInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/ZoomIn-32.png"))); // NOI18N
        ZoomInButton.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(ZoomInButton);

        ZoomOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/ZoomOut-32.png"))); // NOI18N
        ZoomOutButton.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(ZoomOutButton);

        PencilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Edit-32.png"))); // NOI18N
        PencilButton.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(PencilButton);

        PasteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mictgui/icons/Paste-32.png"))); // NOI18N
        PasteButton.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(PasteButton);
    }// </editor-fold>//GEN-END:initComponents

private void CopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CopyButtonActionPerformed

private void CopyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CopyButtonMouseClicked
//CopyButton has been clicked.    
}//GEN-LAST:event_CopyButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CopyButton;
    private javax.swing.JButton CutButton;
    private javax.swing.JButton PasteButton;
    private javax.swing.JButton PencilButton;
    private javax.swing.JButton ZoomInButton;
    private javax.swing.JButton ZoomOutButton;
    // End of variables declaration//GEN-END:variables

}
